<?php // Mitchell Bennis (mitch@elementengage.com)
// Version 1.1 -- Rev 12.15.23
// PHP 8.3 Approved

$eeCountries = array(
	'AU' => 'Australia',
	'AT' => 'Austria',
	'BY' => 'Belarus',
	'BE' => 'Belgium',
	'BG' => 'Bulgaria',
	'BR' => 'Brazil',
	'CA' => 'Canada',
	'HR' => 'Croatia',
	'CZ' => 'Czech Republic',
	'DK' => 'Denmark',
	'EE' => 'Estonia',
	'FI' => 'Finland',
	'FR' => 'France',
	'GE' => 'Georgia',
	'DE' => 'Germany',
	'GR' => 'Greece',
	'GL' => 'Greenland',
	'HT' => 'Haiti',
	'HN' => 'Honduras',
	'HK' => 'Hong Kong',
	'HU' => 'Hungary',
	'IS' => 'Iceland',
	'IN' => 'India',
	'ID' => 'Indonesia',
	'IE' => 'Ireland',
	'IL' => 'Israel',
	'IT' => 'Italy',
	'JM' => 'Jamaica',
	'JP' => 'Japan',
	'JE' => 'Jersey',
	'JO' => 'Jordan',
	'KZ' => 'Kazakhstan',
	'KE' => 'Kenya',
	'KR' => 'Korea',
	'LV' => 'Latvia',
	'LB' => 'Lebanon',
	'LI' => 'Liechtenstein',
	'LT' => 'Lithuania',
	'LU' => 'Luxembourg',
	'MX' => 'Mexico',
	'PY' => 'Paraguay',
	'PE' => 'Peru',
	'PH' => 'Philippines',
	'PL' => 'Poland',
	'PT' => 'Portugal',
	'PR' => 'Puerto Rico',
	'QA' => 'Qatar',
	'RO' => 'Romania',
	'RU' => 'Russian Federation',
	'RS' => 'Serbia',
	'SG' => 'Singapore',
	'SK' => 'Slovakia',
	'SI' => 'Slovenia',
	'ZA' => 'South Africa',
	'ES' => 'Spain',
	'SZ' => 'Swaziland',
	'SE' => 'Sweden',
	'CH' => 'Switzerland',
	'TW' => 'Taiwan',
	'TH' => 'Thailand',
	'TR' => 'Turkey',
	'UG' => 'Uganda',
	'UA' => 'Ukraine',
	'AE' => 'United Arab Emirates',
	'GB' => 'United Kingdom',
	'US' => 'United States',
	'--' => 'Other'
);


?>